# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 794d39cbe0b2fecd67b2f505ac1ab1c6544285c543537a4534ea0adbf018743d86d80fae9ae7eb3ccaa0f3dfb98c3e0195c628d9542ec11461e43b5c5aac07a9

test:
  secret_key_base: 213a8b436838027ca1fa326675a5d7ee2d237c48e44645d41a33801a019953cd3a06439f135427e0a5cf29860441a5c4a0a52c3473d9e64a5f17031d3437c25d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
